apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: goserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: goserver
  template:
    metadata:
      name: "goserver"
      labels:
        app: "goserver"
    spec:
      containers:
        - name: "goserver"
          image: "cleitoon1/hello-go:v2"