version: '3'

services:

  app:
    container_name: app
    build:
      context: ./app
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_USER_PASSWORD=root
      - DB_NAME=nodedb
    depends_on:
      - db
    entrypoint: wait-for db:3306 -t 40 -- ./entrypoint.sh
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    build:
      context: ./nginx
    networks:
      - node-network
    depends_on:
      - app
    ports:
      - 8080:80

networks:
  node-network:
    name: 'node-network'
    driver: bridge