version: '3'

services:

  app:
    image: cleitoon1/node:prod
    container_name: app
    build:
      context: ./app
    networks:
      - node-network
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - db
    ports:
      - 3000:3000
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    name: 'node-network'
    driver: bridge