name: ci-sonarqube-workflow
on: 
  push:
    branches: [develop/modulo-integracao-continua]
jobs:
  check-application:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./03 - integracao continua/sonarqube/go/
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out

    